stages:
  - prepare
  - testing
  - name: deploy
    if: branch = feat/travis

cache:
  timeout: 3600
  directories:
    - $HOME/.cache/$TRAVIS_BUILD_ID/test
    - $HOME/.cache/$TRAVIS_BUILD_ID/dist

jobs:
  include:
    - stage: prepare
      name: Packages Test
      script:
        - echo 'Hello test package' > hello
        - mkdir -p $HOME/.cache/$TRAVIS_BUILD_ID/test
        - cp -r . $HOME/.cache/$TRAVIS_BUILD_ID/test/

    - name: Package Dist
      script:
        - echo 'Hello deploy package' > hello
        - mkdir -p $HOME/.cache/$TRAVIS_BUILD_ID/dist
        - cp -r . $HOME/.cache/$TRAVIS_BUILD_ID/dist/

    - stage: testing
      name: Linter
      git:
        clone: false
      script:
        - echo 'Hello testing 1'
        - cp -r $HOME/.cache/$TRAVIS_BUILD_ID/test/* .
        - cat hello

    - name: Behat
      git:
        clone: false
      script:
        - echo 'Hello testing 2'
        - cp -r $HOME/.cache/$TRAVIS_BUILD_ID/test/* .
        - cat hello

    - stage: deploy
      git:
        clone: false
      script:
        - echo 'Hello deploy'
        - cp -r $HOME/.cache/$TRAVIS_BUILD_ID/dist/* .
        - cat hello

