language: php
os: linux
php:
  - 7.3

stages:
  - prepare
  - testing
  - name: deploy
    if: branch = feat/travis

cache:
  timeout: 3600
  directories:
    - $HOME/.cache/$TRAVIS_BUILD_ID

jobs:
  include:
    - stage: prepare
      name: Packages Test
      script:
        - composer install --no-interaction --prefer-dist --no-progress --no-suggest
        - mkdir -p $HOME/.cache/$TRAVIS_BUILD_ID
        - tar -czf $HOME/.cache/$TRAVIS_BUILD_ID/test.tar.gz .

    - name: Package Dist
      script:
        - composer install --no-interaction --prefer-dist --no-progress --no-suggest --no-dev
        - echo "dist package" > hello
        - tar -czf $HOME/.cache/$TRAVIS_BUILD_ID/dist.tar.gz .

    - stage: testing
      name: Linter
      git:
        clone: false
      script:
        - tar -xzf $HOME/.cache/$TRAVIS_BUILD_ID/test.tar.gz
        - php -l src/dynamic.php

    - name: Behat
      git:
      clone: false
      script:
        - tar -xzf $HOME/.cache/$TRAVIS_BUILD_ID/test.tar.gz
        #- ./vendor/bin/behat -c ./behat.yml --colors -f pretty -vv

    - stage: deploy
      name: Deploy
      git:
        clone: false
      script:
        - tar -xzf $HOME/.cache/$TRAVIS_BUILD_ID/dist.tar.gz
        - ls -lh
        - cat hello
